service: atom-fashion
runtime: nodejs12
env: flex
manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 1000

handlers:
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /
    static_dir: client/build

includes:
  - env_variables.yaml
beta_settings:
  cloud_sql_instances: pbl-demo-2020-281322:asia-northeast1:data-applications

# steps:
#   - name: node:12
#   entrypoint: npm
#   args: ['install']
