service: looker-dat-vision-staging
runtime: nodejs
env: flex
manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    static_files: client/vision/build/index.html
    upload: client/vision/build/index.html
  - url: /
    static_dir: client/vision/build

includes:
  - env_variables.yaml
beta_settings:
  cloud_sql_instances: pbl-demo-2020-281322:asia-northeast1:data-applications
